max_email_length: 50
max_name_length: 50 
min_password_length: 6
image_url: "http://gravatar.com/emails"
hours_expired: 2
gravatar:
  size: 80
  list_size: 50
help_link: "https://tiv.wsm.vn/learn/en/learning/1467/content/618/video/5073/"
valid_email_regex: \A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z
